SUBS = {
    '[1080p]': '',
    '[song]': '',
    '(Song)': '',
    '[Song]': '',
    '(+Lyrics)': '',
    '_Lyrics': '',
    'MLP: FiM': 'MLP -',
    'MLP -FiM': 'MLP -',
    'My Little Pony - Friendship is Magic': 'MLP',
    'My_little_Pony': 'MLP',
    '| Music | ': '',
    '_ Music _ ': '',
    '| HD': '',
    'HD': '',
    ' _ HD': '',
    '(HQ)': '',
    'PMV': '',
    'AMV': '',
    'OST': '',
    'VIP': '',
    'M-V': '',
    '[WIP]': '',
    '[Electro]': '',
    '[HOUSE]': '',
    '[Dubstep]': '',
    '[Now_on_iTunes!]': '',
    '[EUROBEAT]': '',
    '[Hardstyle]': '',
    '[Drum_and_Bass]': '',
    '[Explicit]': '',
    'FULL VERSION': '',
    'full version': '',
    'full_version': '',
    '(video version)': '',
    '(Ultra Music)': '',
    'EPILEPSY_WARNING!': '',
    'EPILEPSY_WARNING': '',
    '[OFFICIAL]': '',
    '[OFFICIAL VIDEO]': '',
    '(Official_Video)': '',
    '(Official Video)': '',
    '(Official videoclip)': '',
    '(Official Music Video)': '',
    '(Official Video HQ)': '',
    '(Out Now)': '',
    'Music Video': '',
    '[Chiptune_8-bit]': '',
    '[]': '',
    ' .mp4': '.mp4',
    '_.mp4': '.mp4',
    '_.mp3': '.mp3',
    '_.mp3': '.mp3',
    '..': '.',
}
